apiVersion: v1

kind : Pod

metadata:
  name: mi-app
  labels:
    app: web

spec:
  containers:
    - name: postgresdb
      image: postgres
      ports:
        - containerPort: 5432

    - name: alpine
      image: "postgres:alpine"