version: "3"

services:
  database:
    container_name: postgres_db
    image: 'postgres'
    ports:
      - "5432:5432"
    env_file:
      - "./database.env"
  app:
    build: .
    ports:
      - "8090:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  postgres:
    image: "postgres:alpine"
